### ISSUE TITLE
About environments

### ISSUE THREAD

**Issue by JOMANL** [navidstuv/NuClick#6]
I appreciate your great work.
If possible, can you share me the details of environments?
I just tried your apps but got some error due to version mismatch of keras and tensorflow.

Best regards

**Comment by navidstuv** [comment]
Hi, Thank you
[Here](https://github.com/navidstuv/NuClick/blob/03feac76bbababca18677b2affc745f0298f427b/requirements.txt#L1)
I updated the Readme as well.
