### ISSUE TITLE
Published datasets in NuClick

### ISSUE THREAD

**Issue by ChaoyueDing** [navidstuv/NuClick#7]
Hello, I saw the following sentence in the paper: " As exemplar outputs of our framework, we are releasing two datasets: 1) a dataset of lymphocyte annotations within IHC images, and 2) a dataset of segmented WBCs in blood smear images.". But I couldn't find the dataset link. Could you kindly tell me where it is?

**Comment by navidstuv** [comment]
Hi,
[Here](https://warwick.ac.uk/fac/sci/dcs/research/tia/data/nuclick/)
I also added it to the Readme
